/* This file was generated by blade */
extern "C" {
namespace binary_version {
extern const int kSvnInfoCount = 0;
extern const char* const kSvnInfo[0] = {};
extern const char kBuildType[] = "release";
extern const char kBuildTime[] = "Mon Aug 27 15:31:57 2018";
extern const char kBuilderName[] = "dengzhilong";
extern const char kHostName[] = "LY1F-R010608";
extern const char kCompiler[] = "GCC 4.8.5";
}}
